# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ad2bcaa61f523ac3c46a8d3132952654d12a451490ed8b982623c5c0e8d4aa186f85114e01e312110d1fd554cc84c6291721afb024eeb7e56e43ac104026ea8

test:
  secret_key_base: e97ee4ab42f6a1b9f7f76ff1ecdb6f17a120bc8639e76e39bfb3ebdc596190a3ce39621cd080a5896402e018a1ac668319fd0bcd297fda5d9f3a188e82d34fd2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
